using Toybox.Application;
using Toybox.Application.Properties;
using Toybox.Graphics;

import Toybox.Lang;


// The time style setting: the woken time drawn filled, on its black box, or hollow, as an
// outline with the rain falling through the digits (#72).
//
// Hollow is only for L and XL. A 1.2-pixel outline, the stroke the fonts are generated
// with, leaves too little of an S or M digit to stand out against the rain, which is the
// same green; those two stay filled on their box whichever style is chosen. So hollow
// changes nothing until the time size is L or XL, and the setting's own label says so.
//
// A hollow font is its filled twin with the interior taken out: the same face and size,
// generated by garmin-font-scaler with a stroke, so the same metrics, and swapping one
// for the other never moves the time. tools/check-font-config.py holds the pairs to that.
module TimeStyle {

    const
        PROPERTY = "timeStyle",
        FILLED = 0,
        HOLLOW = 1;

    // The stored style, clamped by styleOf.
    function selected() as Number {
        return styleOf(PropertyUtils.getPropertyElseDefault(PROPERTY, FILLED));
    }

    // Anything that is not one of the two -- a missing property, a value of the wrong
    // type, one out of range -- is filled, Lite's style.
    function styleOf(value as Properties.ValueType or Null) as Number {
        if (value instanceof Number && (value == FILLED || value == HOLLOW)) {
            return value;
        }
        return FILLED;
    }

    // The hollow font for a time size, or null for a size that has none, S and M. Loaded
    // only when asked for: the two are Premium's largest time bitmaps after XL itself.
    function loadHollow(size as Number) as Graphics.FontType or Null {
        switch (size) {
            case TimeSize.LARGE:
                return Application.loadResource(Rez.Fonts.TimeLargeHollow) as Graphics.FontType;
            case TimeSize.EXTRA_LARGE:
                return Application.loadResource(Rez.Fonts.TimeExtraLargeHollow) as Graphics.FontType;
            default:
                return null;
        }
    }

}
