using Toybox.Application.Properties;

import Toybox.Lang;


// The time style setting: the woken time drawn filled, as solid digits the rain falls
// around, or hollow, as an outline with the rain falling through the digits (#72). Neither
// is drawn on a box (#174); Lite's filled time is, and that look is Lite's alone.
//
// Hollow is only for S and above: S, M, L, XL and XXL. A 1.2-pixel outline, the stroke the
// fonts are generated with, leaves too little of an XXS or XS digit to stand out against
// the rain, which is the same green; those two stay filled whichever style is chosen. So
// hollow changes nothing until the time size is S or larger, and the setting's own label
// says so. (Before #166 there were three hollow sizes, L, XL and XXL, which are today's S,
// M and L; #166 renamed the sizes and added the hollow XL and XXL with the two new sizes.)
//
// A hollow font is its filled twin with the interior taken out: the same face and size,
// generated by garmin-font-scaler with a stroke, so the same metrics, and swapping one
// for the other never moves the time. tools/check-font-config.py holds the pairs to that.
module TimeStyle {

    const
        PROPERTY = "timeStyle",
        FILLED = 0,
        HOLLOW = 1;

    // The stored style, clamped by styleOf.
    function selected() as Number {
        return styleOf(PropertyUtils.getPropertyElseDefault(PROPERTY, FILLED));
    }

    // Anything that is not one of the two -- a missing property, a value of the wrong
    // type, one out of range -- is filled, Lite's style.
    function styleOf(value as Properties.ValueType or Null) as Number {
        if (value instanceof Number && (value == FILLED || value == HOLLOW)) {
            return value;
        }
        return FILLED;
    }

    // The hollow font a size is drawn in under the given style, or null where the time is
    // drawn filled: the filled style, or a size with no hollow font, XXS and XS.
    //
    // An id rather than a loaded font, because it is the one decision the draw follows:
    // DigitalRain picks its font from this value. Two loaded fonts cannot be told apart by
    // what they hold -- only whether they are the same object -- but two ids can, which is
    // what lets TimeStyleTest check the choice itself.
    function hollowFont(size as Number, style as Number) as ResourceId or Null {
        if (style != HOLLOW) {
            return null;
        }
        switch (size) {
            case TimeSize.SMALL:
                return Rez.Fonts.TimeLargeHollow;
            case TimeSize.MEDIUM:
                return Rez.Fonts.TimeExtraLargeHollow;
            case TimeSize.LARGE:
                return Rez.Fonts.TimeExtraExtraLargeHollow;
            case TimeSize.EXTRA_LARGE:
                return Rez.Fonts.TimeHugeHollow;
            case TimeSize.EXTRA_EXTRA_LARGE:
                return Rez.Fonts.TimeExtraHugeHollow;
            default:
                return null;
        }
    }

    // Premium's always-on font: the filled XL, 96 at the reference, whatever the size and
    // style chosen for the woken screen (#164). It was hollow before, the hollow L (#153; the
    // hollow M before it, #145), but a thin outline lights so few pixels that it all but
    // vanished on the panel the watch dims in always-on. Defined through TimeSize.fontOf so
    // that it is the woken filled XL by construction, which is what lets DigitalRain draw
    // both from one loaded font. An id for the reason hollowFont gives: LowPowerFontTest
    // checks it is the filled one, which a loaded font could not show, since filled and
    // hollow XL share every metric.
    function alwaysOnFont() as ResourceId {
        return TimeSize.fontOf(TimeSize.EXTRA_LARGE);
    }

}
